import type { Metadata } from "next";
import { Geist, Geist_Mono, Crimson_Pro, Crimson_Text } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const CrimsonPro = Crimson_Pro({
  variable: "--font-crimson-sans",
  subsets: ['latin']
});

const CrimsonText = Crimson_Text({
  variable: "--font-crimsonText-sans",
  subsets: ['latin'],
  weight: ['400', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  ${CrimsonPro.variable} ${CrimsonText.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
